# Generated by Django 4.0.5 on 2022-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
