# Generated by Django 4.0.5 on 2022-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system1', '0002_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='+xxxxxxxxxx', max_length=15),
        ),
    ]
