# Generated by Django 4.0.5 on 2022-07-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['grade', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system2.classroom')),
                ('lecture', models.ManyToManyField(related_name='lecture', to='system2.lectures')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system2.lectures')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system2.student')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='lectures',
            field=models.ManyToManyField(related_name='lectures', to='system2.lectures'),
        ),
    ]
