# Generated by Django 4.0.5 on 2022-07-30 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system2.classroom')),
                ('lecture', models.ManyToManyField(related_name='room_lecture', to='system2.lectures')),
            ],
        ),
    ]
